### ISSUE TITLE
The recovery server could not be contacted [Error during installation]

### ISSUE THREAD

**Issue by afridi26** [sickcodes/Docker-OSX#123]
Hey,

I am behind a proxy. To run this docker container, I follow the instructions as specified in the README file and had also gone through boot [instructions](https://github.com/sickcodes/Docker-OSX#additional-boot-instructions).

I ran the following command and the screen is shown to me:
```
docker run \
    --device /dev/kvm \
    -p 50922:10022 \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -e "DISPLAY=${DISPLAY:-:0.0}" \
    sickcodes/docker-osx:latest
```
I am getting the following error during installation.

![image](https://user-images.githubusercontent.com/5488091/104177115-4921f100-53d6-11eb-95da-20e1d0537ed7.png)

Any help would be appreciated.

Thanks.

**Comment by Element21** [comment]
You have to set the rtc to your correct time. Open a terminal and run `date Month Date Hour Minute Year without any separation.` For example `date 0712122318` would be “July 12 2018 at 12:23”

**Comment by afridi26** [comment]
Hey @Element21,

Thank you for your valuable time.

I make changes as per your instruction but getting the same error.

![image](https://user-images.githubusercontent.com/5488091/104310892-763bd580-54a2-11eb-80e4-d375e81db3ed.png)

But I am getting this error. Any idea why?

Thanks.

**Comment by Element21** [comment]
Hmmmmm. That fixed it for me

**Comment by sickcodes** [comment]
Might be country of origin. Try a VPN?

**Comment by rabinhod** [comment]
I fixed with this link

https://www.edureka.co/community/12726/my-docker-container-has-no-internet

**Comment by afridi26** [comment]
@rabinhod Hey Thanks,

I tried but the problem persists.

Regards,
Aftab

**Comment by sickcodes** [comment]
When you open the Safari browser in the recovery disk, do websites load?

**Comment by sickcodes** [comment]
Tbh it has to do with the proxy, Docker obeys the two environment variables below:

export HTTP_PROXY=1.1.1.1
export HTTPS_PROXY=1.1.1.1
sudo killall dockerd && sudo dockerd

**Comment by afridi26** [comment]
I tried to load a website in safari browser but its not wokring. I am sure it is internet issue. I am behind the proxy and connected via anyconnect.

If I am able to install openeconnect somehow inside the container, then I can get access to public internet. I am trying to update the Dockerfile, so to install openconnect and then use it? What you say is it a good idea?

**Comment by rabinhod** [comment]
@afridi26
I think the problem is your container doesn't have access to internet and it's not about macOs
at least you should be able to have ping to 8.8.8.8 from container

and then i use openvpn in my host to continue installing ( اینجا ایرانه دیگه مجوریم )

**Comment by sickcodes** [comment]
You have to force the docker daemon to use the proxy. This is a Docker problem with your anyconnect VPN. Try a different VPN. Add a firewall rule to send docker traffic through the anyconnect VPN.
