### ISSUE TITLE
Memory panic on mac os monterey

### ISSUE THREAD

**Issue by sjhaleprogrammer** [sickcodes/Docker-OSX#401]
Linux samuel-rogzephyrusg15ga503qrga503qr 5.15.6-arch2-1 #1 SMP PREEMPT Thu, 02 Dec 2021 15:47:09 +0000 x86_64 GNU/Linux
:0.0

![image](https://user-images.githubusercontent.com/60676867/144723290-cdefa514-bd84-4a15-a6f6-d76c7d7821bb.png)

getting memory panic on monterey

**Comment by MikeCoder96** [comment]
[Duplicate Here](https://github.com/sickcodes/Docker-OSX/issues/380)

**Comment by sickcodes** [comment]
Anyone getting CPU errors, these should fix the problem, if so, please let me know and Ill update the readme

```
# Catalina, Big Sur
    -e MASTER_PLIST_URL='https://raw.githubusercontent.com/sickcodes/osx-serial-generator/d5f3ff3f81d13d696556b78024fbebde8e5b7281/config-custom.plist \

# Self PR for Monterey
    -e MASTER_PLIST_URL='https://raw.githubusercontent.com/sickcodes/osx-serial-generator/811c14c4b43ba4d0b20a22480975a91e3e176d72/config-custom.plist' \

# Master
    -e MASTER_PLIST_URL='https://raw.githubusercontent.com/sickcodes/osx-serial-generator/master/config-custom.plist' \
```

**Comment by sickcodes** [comment]
This should be fixed in all images, please reply if it has not

**Comment by backtolife2021** [comment]
```fish
docker run -it \
          --device /dev/kvm \
          -p 50922:10022 \
          -v /tmp/.X11-unix:/tmp/.X11-unix \
          -e "DISPLAY=:0" \
          -e GENERATE_UNIQUE=true \
          -e MASTER_PLIST_URL='https://raw.githubusercontent.com/sickcodes/osx-serial-generator/811c14c4b43ba4d0b20a22480975a91e3e176d72/config-custom.plist' \
          sickcodes/docker-osx:monterey
```
![image](https://user-images.githubusercontent.com/24669431/148921188-77253761-88f8-4dd3-aca3-8fb975265d4b.png)

**Comment by koningcool** [comment]
I have the issue still on the Monterey one, I don't know if others work, can someone help me with this?

**Comment by sickcodes** [comment]
It's usually due to incompatible CPU; or you haven't set up KVM correctly

**Comment by 2shrestha22** [comment]
Same error for me. Was working before, did all the setup and today I updated my ArchLinux now it does not start. Catalina works Monterey does not.

**Comment by sickcodes** [comment]
Should be fixed today. 5.18.9

may required `modprobe msr cpuid`

**Comment by imunique-ZJ** [comment]
Still getting same error on Monterey but works on Catalina and Big-Sur.
=====
OS: ubuntu 22.04.1 LTS
CPU: AMD 4800U

![image](https://user-images.githubusercontent.com/4104660/196016062-185f24ce-58cb-4895-b82f-62203f6b0b11.png)

**Comment by smurfxx** [comment]
I get this error installing catalina on a Legion 5 with AMD Ryzen 7 4800H and this command:
sudo docker run -it --device /dev/kvm -p 50922:10022 -v /tmp/.X11-unix:/tmp/.X11-unix -e "DISPLAY=${DISPLAY:-:0.0}" -e RAM=8 -e GENERATE_UNIQUE=true -e MASTER_PLIST_URL='https://raw.githubusercontent.com/sickcodes/osx-serial-generator/master/config-custom.plist' sickcodes/docker-osx:ventura

**Comment by nullchilly** [comment]
I was able to boot past MACH REBOOT using command from @asies23 on discord

Quote: This is the command I had to use to finally make it boot past the MACH Reboot Error

```sh
docker run -it \
    --device /dev/kvm \
    -p 50922:10022 \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -e "DISPLAY=${DISPLAY:-:0.0}" \
    -e GENERATE_UNIQUE=true \
    -e MASTER_PLIST_URL='https://raw.githubusercontent.com/sickcodes/osx-serial-generator/master/config-custom.plist' \
    -e "RAM=8" \
    -e CPU='Haswell-noTSX,vendor=GenuineIntel,+invtsc,+hypervisor,kvm=on,vmware-cpuid-freq=on' \
    -e EXTRA="-smp 8,sockets=1,cores=4,threads=2" \
    sickcodes/docker-osx:ventura

# docker build -t docker-osx --build-arg SHORTNAME=ventura .
```

<img width="1280" alt="image" src="https://github.com/sickcodes/Docker-OSX/assets/56817415/1c82b924-5082-4df2-b1ab-88b2030101a2">
