### ISSUE TITLE
Unable to run macOS docker images after kernel upgrade to 5.18

### ISSUE THREAD

**Issue by jorainer** [sickcodes/Docker-OSX#512]
After updating from kernel 5.17 (5.17.9-arch1-1) to kernel 5.18 I'm unable to run macOS with the docker images. I've tried it with the Monterey image which runs nicely with the old kernel but gets stuck right after the boot screen (where it is possible to select either *macOS Base System*, *UEFI Shell* etc).

Does anyone else have similar problem? Any feedback welcome.

The output from the commands to get info on my system are below:

```
Linux rocinante 5.18.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 25 Jun 2022 20:22:01 +0000 x86_64 GNU/Linux
:0
[sudo] password for jo: 
1
NAME="ArchLabs"
PRETTY_NAME="ArchLabs Linux"
Filesystem      Size  Used Avail Use% Mounted on
/dev/nvme0n1p2  1.8T  1.6T  172G  91% /
QEMU emulator version 7.0.0
Copyright (c) 2003-2022 Fabrice Bellard and the QEMU Project developers
libvirtd (libvirt) 8.4.0
               total        used        free      shared  buff/cache   available
Mem:            62Gi       2.4Gi        58Gi       531Mi       1.7Gi        59Gi
Swap:           62Gi          0B        62Gi
8
16
crw-rw-rw- 1 root kvm 10, 232 Jun 28 16:54 /dev/kvm
total 0
drwxrwxrwt  2 root root  100 Jun 28 16:55 .
drwxrwxrwt 15 root root  340 Jun 28 16:57 ..
srwxrwxrwx  1 jo   users   0 Jun 28 16:55 X0
srwxr-xr-x  1 gdm  gdm     0 Jun 28 16:55 X1024
srwxr-xr-x  1 gdm  gdm     0 Jun 28 16:55 X1025
root         501  0.1  0.1 1816364 73104 ?       Ssl  16:54   0:00 /usr/bin/dockerd -H fd://
jo          3143  0.0  0.0   6684  2648 pts/2    S+   16:57   0:00 grep --color=auto dockerd
kvm:x:992:libvirt-qemu,qemu,jo
libvirt:x:970:jo
libvirt-qemu:x:964:
docker:x:959:jo
```

**Comment by sickcodes** [comment]
Confirmed on 5.18.8

**Comment by sickcodes** [comment]
Fixed on 5.18.9, may require `sudo modprobe msr cpuid`

**Comment by jorainer** [comment]
For me it was still not working with >= 5.18.9 but using the solution from [here](https://www.reddit.com/r/archlinux/comments/v0x3c4/psa_if_you_run_kernel_518_with_nvidia_pass_ibtoff/) or [here](https://bbs.archlinux.org/viewtopic.php?id=276699) worked.

Essentially, KVM was broken on my computer (11th generetion Intel CPU) and adding `ibt=off` as kernel parameter solved it. Seems to be a thing specific to 11th gen Intels and kernel >= 5.18.
